// Fetches Andaaza's icons from Iconify once and writes them into public/index.html (between ICONS:BEGIN and
// ICONS:END), so the page never calls Iconify at run time. Run by hand when the list below changes:
//   npm run icons
// Material Symbols, rounded (Apache 2.0); brand marks from Simple Icons (CC0), single-colour by design.
// Trademarks belong to their owners.
import { readFileSync, writeFileSync } from "node:fs";
import { optimize } from "svgo";

const ICON_LIST = {
  "a:sport": "material-symbols:exercise-rounded", "a:tech": "material-symbols:memory-rounded", "a:money": "material-symbols:payments-rounded",
  "a:world": "material-symbols:globe-asia-rounded", "a:screen": "material-symbols:theaters-rounded", "a:misc": "material-symbols:auto-awesome-rounded",
  "a:moves": "material-symbols:monitoring-rounded", "a:globe": "material-symbols:public-rounded",
  "t:f1": "material-symbols:sports-score-rounded", "t:football": "material-symbols:sports-soccer-rounded", "t:cricket": "material-symbols:sports-cricket-rounded",
  "t:tennis": "material-symbols:sports-tennis-rounded", "t:nba": "material-symbols:sports-basketball-rounded", "t:ai": "material-symbols:memory-rounded",
  "t:money": "material-symbols:trending-up-rounded", "t:india": "material-symbols:flag-rounded", "t:world": "material-symbols:public-rounded",
  "t:film": "material-symbols:movie-rounded", "t:ott": "material-symbols:live-tv-rounded", "t:celebs": "material-symbols:star-rounded",
  "u:moon": "material-symbols:dark-mode-rounded", "u:sun": "material-symbols:light-mode-rounded", "u:poster": "material-symbols:filter-frames-rounded", "u:speak": "material-symbols:volume-up-rounded",
  "s:instagram": "simple-icons:instagram", "s:linkedin": "simple-icons:linkedin", "u:retro": "material-symbols:radio-rounded", "s:claude": "simple-icons:claude",
  "s:gemini": "simple-icons:googlegemini",
};

async function build(WANT) {
  const byPrefix = {};
  for (const [k, v] of Object.entries(WANT)) { const [p, n] = v.split(":"); (byPrefix[p] ||= new Map()).set(n, [...(byPrefix[p].get(n) || []), k]); }
  const out = {};
  for (const [p, names] of Object.entries(byPrefix)) {
    const r = await fetch(`https://api.iconify.design/${p}.json?icons=${[...names.keys()].join(",")}`);
    const j = await r.json();
    for (const [n, keys] of names) {
      const icon = j.icons?.[n] || j.icons?.[j.aliases?.[n]?.parent];
      if (!icon) { console.error(`missing ${p}:${n}`); continue; }
      const w = icon.width || j.width || 24, h = icon.height || j.height || 24;
      // Marks are drawn at 14 to 54 px: one decimal of a 24-unit box is plenty.
      const svg = optimize(`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${w} ${h}">${icon.body}</svg>`, { multipass: true, floatPrecision: w > 100 ? 0 : 1, plugins: ["preset-default"] }).data;
      const body = svg.replace(/^<svg[^>]*>|<\/svg>$/g, "");
      for (const k of keys) out[k] = [`0 0 ${w} ${h}`, body];
    }
  }
  const bodies = [], ref = {};
  for (const [k, v] of Object.entries(out)) { const key = v.join("|"); let i = bodies.findIndex(b => b.join("|") === key); if (i < 0) i = bodies.push(v) - 1; ref[k] = i; }
  const block = `// ICONS:BEGIN (generated by scripts/icons.mjs from Iconify: Material Symbols, Simple Icons; do not edit by hand)\nconst ICONS = {};\n{ const B = ${JSON.stringify(bodies)}, R = ${JSON.stringify(ref)}; for (const k in R) ICONS[k] = B[R[k]]; }\n// ICONS:END`;
  return { block, count: Object.keys(out).length };
}
const put = (file, block, anchor) => {
  const src = readFileSync(file, "utf8");
  const next = /\/\/ ICONS:BEGIN[\s\S]*?\/\/ ICONS:END/.test(src) ? src.replace(/\/\/ ICONS:BEGIN[\s\S]*?\/\/ ICONS:END/, block) : src.replace(anchor, `${block}\n${anchor}`);
  if (next === src && !src.includes(block)) throw new Error(`no place for icons in ${file}`);
  writeFileSync(file, next);
};
const C = await build(ICON_LIST);
put("public/index.html", C.block, "const $ = s => document.querySelector(s);");
console.log(`icons: ${C.count} into public/index.html (${(C.block.length / 1024).toFixed(1)} KB)`);
