// Fetches the logos, flags and marks named in config/logos.json from Iconify once, and writes them with the name list
// into public/logos.js, which the page loads after it has shown the markets. The page never calls Iconify.
// Run by hand when config/logos.json changes:
//   npm run logos
// Sources and licences are listed in config/logos.json ("sources"). Trademarks belong to their owners.
import { readFileSync, writeFileSync } from "node:fs";
import { optimize } from "svgo";

const C = JSON.parse(readFileSync("config/logos.json", "utf8"));
// The same folding the page uses: no case, no accents, only letters, digits and single spaces.
const norm = t => String(t).toLowerCase().normalize("NFD").replace(/[̀-ͯ]/g, "").replace(/[^a-z0-9]+/g, " ").trim();
const clean = o => Object.fromEntries(Object.entries(o).filter(([k]) => !k.startsWith("$")));

// Every icon wanted, by set: brands and competitions as given, flags from circle-flags.
const want = new Set([...Object.values(clean(C.brands)), ...Object.values(clean(C.competitions)),
  ...[...Object.values(clean(C.countries)), ...Object.values(clean(C.people))].map(c => `circle-flags:${c}`)]);
const bySet = {};
for (const id of want) { const [p, n] = id.split(":"); (bySet[p] ||= new Set()).add(n); }

const icons = {}, missing = [];
for (const [p, names] of Object.entries(bySet)) {
  const list = [...names];
  for (let i = 0; i < list.length; i += 60) {
    const part = list.slice(i, i + 60);
    const r = await fetch(`https://api.iconify.design/${p}.json?icons=${part.join(",")}`);
    const j = r.ok ? await r.json() : {};
    for (const n of part) {
      const icon = j.icons?.[n] || j.icons?.[j.aliases?.[n]?.parent];
      if (!icon) { missing.push(`${p}:${n}`); continue; }
      const w = icon.width || j.width || 24, h = icon.height || j.height || 24;
      const svg = optimize(`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${w} ${h}">${icon.body}</svg>`,
        { multipass: true, floatPrecision: w > 100 ? 0 : 1, plugins: [{ name: "preset-default", params: { overrides: { removeViewBox: false } } }] }).data;
      // Round flags carry a circular mask with a shared id ("a"); the page rounds them with CSS instead, so the mask
      // goes and no two marks on a page can clash over an id.
      let body = svg.replace(/^<svg[^>]*>|<\/svg>$/g, "").replace(/<mask id="a">.*?<\/mask>/, "").replace(/ mask="url\(#a\)"/g, "");
      if (/\bid="/.test(body)) { missing.push(`${p}:${n} (has ids)`); continue; }
      icons[`${p}:${n}`] = [`0 0 ${w} ${h}`, body];
    }
  }
}

// name → mark: "i:<icon>" (a brand, in the text colour), "f:<icon>" (a flag, in its own colours), "t:RM" (a monogram).
const names = {};
for (const [k, v] of Object.entries(clean(C.brands))) if (icons[v]) names[norm(k)] = `i:${v}`;
for (const [k, v] of Object.entries(clean(C.monograms))) names[norm(k)] = `t:${v}`;
for (const [k, v] of Object.entries({ ...clean(C.countries), ...clean(C.people) })) if (icons[`circle-flags:${v}`]) names[norm(k)] = `f:circle-flags:${v}`;
const comps = {};
for (const [k, v] of Object.entries(clean(C.competitions))) if (icons[v]) comps[norm(k)] = v;

const out = `// Generated by scripts/logos.mjs from config/logos.json (Iconify: Simple Icons, Arcticons, Circle Flags and others;
// licences in config/logos.json). Do not edit by hand: edit config/logos.json and run \`npm run logos\`.
window.ANDAAZA_LOGOS = ${JSON.stringify({ icons, names, comps })};
window.onAndaazaLogos && window.onAndaazaLogos();
`;
writeFileSync("public/logos.js", out);
console.log(`logos: ${Object.keys(icons).length} marks, ${Object.keys(names).length} names, ${Object.keys(comps).length} competitions, ${(out.length / 1024).toFixed(1)} KB`);
if (missing.length) console.log(`not found (left out): ${missing.join(", ")}`);
